FIND_PACKAGE(R REQUIRED RInside)

SET(SIM_INCLUDE_DIRS ${R_INCLUDE_DIRS} ${R_RCPP_INCLUDE_DIR} ${R_RINSIDE_INCLUDE_DIR})

SET(SIM_LIBRARY_DIRS ${R_LIBRARY_DIRS} ${R_RCPP_LIBRARY_DIR} ${R_RINSIDE_LIBRARY_DIR})

SET(SIM_LINK_LIBS ${R_LIBRARIES} ${R_RCPP_LIBRARIES} ${R_RINSIDE_LIBRARIES})

