#!/bin/sh

# Called by "git push" after it has checked the remote status, but before anything has been
# pushed.  If this script exits with a non-zero status nothing will be pushed.
#
# This hook is called with the following parameters:
#
# $1 -- Name of the remote to which the push is being done
# $2 -- URL to which the push is being done
#
# If pushing without using a named remote those arguments will be equal.
#
# Information about the commits which are being pushed is supplied as lines to
# the standard input in the form:
#
#   <local ref> <local sha1> <remote ref> <remote sha1>
#
# This sample shows how to prevent push of commits where the log message starts
# with "WIP" (work in progress).

remote="$1"
url="$2"

z40=0000000000000000000000000000000000000000

while read local_ref local_sha remote_ref remote_sha
do
	if [ "$local_sha" = $z40 ]
	then
		# Handle delete
		:
	else
        case "$local_ref" in 
          *wip*)
            # wip branch, tolerant with WIP commits
            ;;
          *)
            if [ "$remote_sha" = $z40 ]
            then
                # New branch, examine all commits
                range="$local_sha"
            else
                # Update to existing branch, examine new commits
                range="$remote_sha..$local_sha"
            fi

            # Check for WIP commit
            commit=`git rev-list -n 1 --grep 'WIP' "$range"`
            if [ -n "$commit" ]
            then
                echo >&2 "Found WIP commit in $local_ref, not pushing"
                exit 1
            fi
            ;;
        esac
	fi
done

### Check stylecheck before pushing

REPO_ROOT=$(git rev-parse --show-toplevel)

$REPO_ROOT/resources/tools/ofsrc-stylecheck.py $REPO_ROOT --disable=UNRT --exclude=share/openfluid/waresdev/templates,resources/tests/miscsrc/cmdline-check,examples/wares-dev


# Capture the return value
RETURN_VALUE=$?

# Check the return value
if [ $RETURN_VALUE -ne 0 ]; then
  echo "Pre-commit hook failed: Third-party script returned a non-zero value ($RETURN_VALUE)"
  exit 1
fi

# If everything is okay, exit with 0
exit 0

