stages:
  - test
  - package
  - downstream

test-of:
  stage: test
  image: "registry.forge.inrae.fr/openfluid/interne/openfluid-devtools/ofbuild/debian-13-qt6"
  script:
    - mkdir ./_build
    - cd ./_build && cmake .. -DOFBUILD_ENABLE_DOCS=OFF -DOFBUILD_ENABLE_GUI=OFF
    - make stylecheck
    - make -j `nproc`
    - ctest -j 4 --output-on-failure

test-of-unix-full:
  stage: test
  when: manual
  parallel:
    matrix:
      - TAG: ["debian-13-qt6",
              "ubuntu-24.10-qt6",
              "ubuntu-26.04-qt6",
              "fedora-42-qt6"]
  image: "registry.forge.inrae.fr/openfluid/interne/openfluid-devtools/ofbuild/$TAG"
  script:
    - mkdir ./_build
    - cd ./_build && cmake .. -DOFBUILD_ENABLE_DOCS=OFF -DOFBUILD_ENABLE_GUI=OFF
    - make -j `nproc`
    - ctest -j 4 --output-on-failure

pkg-of-no-ui:
  stage: package
  image: "registry.forge.inrae.fr/openfluid/interne/openfluid-devtools/ofbuild/debian-13-qt6"
  script:
    - mkdir ./_build_noui
    - cd ./_build_noui && cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr -DOFBUILD_ENABLE_GUI=OFF
    - make -j `nproc`
    - cpack -j `nproc`
  artifacts:
    paths:
      - /builds/openfluid/incubateur/openfluid/_build_noui/*.deb

pkg-of-full-deb:
  stage: package
  when: manual
  parallel:
    matrix:
      - TAG: ["debian-13-qt6",
              "ubuntu-24.10-qt6",
              "ubuntu-26.04-qt6"]
  image: "registry.forge.inrae.fr/openfluid/interne/openfluid-devtools/ofbuild/$TAG"
  script:
    - mkdir ./_build_release
    - cd ./_build_release && cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr
    - make -j `nproc`
    - cpack -j `nproc`
  artifacts:
    paths:
      - /builds/openfluid/incubateur/openfluid/_build_release/*.deb


pkg-of-full-rpm:
  stage: package
  when: manual
  parallel:
    matrix:
      - TAG: ["fedora-42-qt6"]
  image: "registry.forge.inrae.fr/openfluid/interne/openfluid-devtools/ofbuild/$TAG"
  script:
    - mkdir ./_build_release
    - cd ./_build_release && cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr
    - export QA_SKIP_RPATHS=1
    - make -j `nproc`
    - cpack -j `nproc`
  artifacts:
    paths:
      - /builds/openfluid/incubateur/openfluid/_build_release/*.rpm

pkg-bindings-r:
  stage: downstream
  image: "registry.forge.inrae.fr/openfluid/interne/openfluid-devtools/ofbuild/debian-13-qt6"
  before_script:
    - sudo apt-get update && sudo apt-get install -y /builds/openfluid/incubateur/openfluid/_build_noui/*.deb
  script:
    - mkdir downstream && cd downstream
    - git clone https://forge.inrae.fr/openfluid/ropenfluid.git
    - cd ropenfluid
    - cmake -P check.cmake
    - cmake -P build.cmake
  artifacts:
    paths:
      - /builds/openfluid/incubateur/openfluid/downstream/ropenfluid/_build/*.tar.gz


pkg-bindings-py:
  stage: downstream
  image: "registry.forge.inrae.fr/openfluid/interne/openfluid-devtools/ofbuild/debian-13-qt6"
  before_script:
    - sudo apt-get update && sudo apt-get install -y /builds/openfluid/incubateur/openfluid/_build_noui/*.deb
  script:
    - mkdir downstream && cd downstream
    - git clone https://forge.inrae.fr/openfluid/pyopenfluid.git
    - cd pyopenfluid
    - python3 setup.py check
    - python3 setup.py build
    - python3 setup.py test
    - python3 setup.py sdist bdist
  artifacts:
    paths:
      - /builds/openfluid/incubateur/openfluid/downstream/pyopenfluid/dist/*.tar.gz


# build-of-container-ubuntu-22-04:
#   stage: container
#   image: docker:24.0.5-cli
#   services:
#     - docker:24.0.5-dind
#   variables:
#     DOCKER_TLS_CERTDIR: ""
#     DOCKER_HOST: tcp://docker:2375
#   script:
#     - |
#         cat > Dockerfile <<EOF
#         FROM ubuntu:22.04
#         COPY openfluid_2.2.1~beta2_jammy_amd64.deb /tmp/
#         RUN apt-get update && apt-get install -y /tmp/openfluid_2.2.1~beta2_jammy_amd64.deb && rm /tmp/openfluid_2.2.1~beta2_jammy_amd64.deb
#         EOF
#     - docker build -t registry.forge.inrae.fr/openfluid/incubateur/openfluid/openfluid:2.2.1b1-ubuntu-22.04-qt5 . 
#     - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
#     - docker push registry.forge.inrae.fr/openfluid/incubateur/openfluid/openfluid:2.2.1b1-ubuntu-22.04-qt5

# Warning: relies on machine-dependant structure, especially custom buildOFwin_ci.ps1 and testOFwin_ci.ps1 scripts
# TODO set automatic when build kill functional
test-of-windows:
  stage: test
  when: manual
  timeout: 20m
  tags: [ windows ]
  variables:
    MINGW64_EXE: "C:\\msys64_for_ofbuild_qt6\\mingw64.exe"

  script: 
    - Start-Process -FilePath "$MINGW64_EXE" -ArgumentList "/usr/bin/bash", "./.gitlab/buildOFwin_ci.sh" -NoNewWindow -Wait
    - find ./_build/build_out.log "Built target observer-export.vars.files.csv-multicols"
    - Start-Process -FilePath "$MINGW64_EXE" -ArgumentList "/usr/bin/bash", "./.gitlab/testOFwin_ci.sh" -NoNewWindow -Wait
    - find ./_build/test_out.log "100% tests passed"
  
  artifacts:
    when: always
    paths:
      - ./_build/*.log

# TODO add Windows-package