stages:
  - test
  - package
  - downstream
  - container

test-of:
  stage: test
  image: "registry.forge.inrae.fr/openfluid/interne/openfluid-devtools/ofbuild/debian-13-qt6"
  script:
    - mkdir ./_build
    - cd ./_build && cmake .. -DOFBUILD_ENABLE_DOCS=OFF -DOFBUILD_ENABLE_GUI=OFF
    - make stylecheck
    - make -j `nproc`
    - ctest -j 3 --output-on-failure
    - ctest --rerun-failed --output-on-failure

test-of-unix-full:
  stage: test
  when: manual
  parallel:
    matrix:
      - TAG: ["debian-13-qt6",
              "ubuntu-24.10-qt6",
              "ubuntu-26.04-qt6",
              "fedora-42-qt6"]
  image: "registry.forge.inrae.fr/openfluid/interne/openfluid-devtools/ofbuild/$TAG"
  script:
    - mkdir ./_build
    - cd ./_build && cmake .. -DOFBUILD_TESTS_ENABLE_HEAVY=ON
    - make -j `nproc`
    - ctest -j 3 --output-on-failure
    - ctest --rerun-failed --output-on-failure

pkg-of-no-ui:
  stage: package
  image: "registry.forge.inrae.fr/openfluid/interne/openfluid-devtools/ofbuild/ubuntu-26.04-qt6"
  script:
    - mkdir ./_build_noui
    - cd ./_build_noui && cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr -DOFBUILD_ENABLE_GUI=OFF
    - make -j `nproc`
    - cpack -j `nproc`
  artifacts:
    paths:
      - _build_noui/*.deb

pkg-of-full-deb:
  stage: package
  when: manual
  parallel:
    matrix:
      - TAG: ["debian-13-qt6",
              "ubuntu-22.04-qt6",
              "ubuntu-24.04-qt6",
              "ubuntu-24.10-qt6"]
  image: "registry.forge.inrae.fr/openfluid/interne/openfluid-devtools/ofbuild/$TAG"
  script:
    - mkdir ./_build_release
    - cd ./_build_release && cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr
    - make -j `nproc`
    - cpack -j `nproc`
  artifacts:
    paths:
      - _build_release/*.deb

pkg-of-lts:
  stage: package
  image: "registry.forge.inrae.fr/openfluid/interne/openfluid-devtools/ofbuild/ubuntu-26.04-qt6"
  script:
    - mkdir ./_build_lts
    - cd ./_build_lts && cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr
    - make -j `nproc`
    - cpack -j `nproc`
  artifacts:
    paths:
      - _build_lts/*.deb

pkg-of-full-rpm:
  stage: package
  when: manual
  parallel:
    matrix:
      - TAG: ["fedora-42-qt6"]
  image: "registry.forge.inrae.fr/openfluid/interne/openfluid-devtools/ofbuild/$TAG"
  script:
    - mkdir ./_build_release
    - cd ./_build_release && cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr
    - export QA_SKIP_RPATHS=1
    - make -j `nproc`
    - cpack -j `nproc`
  artifacts:
    paths:
      - _build_release/*.rpm

pkg-bindings-r:
  stage: downstream
  image: "registry.forge.inrae.fr/openfluid/interne/openfluid-devtools/ofbuild/ubuntu-26.04-qt6"
  needs:
    - pkg-of-no-ui
  before_script:
    - sudo apt-get update && sudo apt-get install -y ./_build_noui/*.deb
  script:
    - mkdir downstream && cd downstream
    - git clone https://forge.inrae.fr/openfluid/ropenfluid.git
    - cd ropenfluid
    - cmake -P check.cmake
    - cmake -P build.cmake
  artifacts:
    paths:
      - downstream/ropenfluid/_build/*.tar.gz


pkg-bindings-py:
  stage: downstream
  when: manual
  needs:
    - pkg-of-no-ui
  image: "registry.forge.inrae.fr/openfluid/interne/openfluid-devtools/ofbuild/debian-13-qt6"
  before_script:
    - sudo apt-get update && sudo apt-get install -y ./_build_noui/*.deb
  script:
    - mkdir downstream && cd downstream
    - git clone https://forge.inrae.fr/openfluid/pyopenfluid.git
    - cd pyopenfluid
    - python3 setup.py check
    - python3 setup.py build
    - python3 setup.py test
    - python3 setup.py sdist bdist
  artifacts:
    paths:
      - downstream/pyopenfluid/dist/*.tar.gz


build-of-container:
  stage: container
  image: docker:24.0.5-cli
  when: manual
  needs:
    - pkg-of-lts
  dependencies:
    - pkg-of-lts
  services:
    - docker:24.0.5-dind
  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: tcp://docker:2375
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
    - cp _build_lts/*.deb openfluid.deb
    - cp resources/packaging/docker/Dockerfile_installOF Dockerfile
  script:
    - docker build -t "$CI_REGISTRY_IMAGE-from_ci:latest" .
    - docker push "$CI_REGISTRY_IMAGE-from_ci:latest"

build-of-container-noui:
  stage: container
  image: docker:24.0.5-cli
  when: manual
  needs:
    - pkg-of-no-ui
  dependencies:
    - pkg-of-no-ui
  services:
    - docker:24.0.5-dind
  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: tcp://docker:2375
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
    - cp _build_noui/*.deb openfluid.deb
    - cp resources/packaging/docker/Dockerfile_installOF Dockerfile
  script:
    - docker build -t "$CI_REGISTRY_IMAGE-from_ci-noui:latest" .
    - docker push "$CI_REGISTRY_IMAGE-from_ci-noui:latest"

# Warning: relies on machine-dependant structure
# TODO set automatic when build kill functional
test-of-windows:
  stage: test
  when: manual
  timeout: 20m
  tags: [ windows ]
  variables:
    MINGW64_EXE: "C:\\msys64_for_ofbuild_qt6\\mingw64.exe"

  script: 
    - Start-Process -FilePath "$MINGW64_EXE" -ArgumentList "/usr/bin/bash", "./.gitlab/buildOFwin_ci.sh" -NoNewWindow -Wait
    - find ./_build/build_out.log "Built target observer-export.vars.files.csv-multicols"
    - Start-Process -FilePath "$MINGW64_EXE" -ArgumentList "/usr/bin/bash", "./.gitlab/testOFwin_ci.sh" -NoNewWindow -Wait
    - find ./_build/test_out.log "100% tests passed"
  
  artifacts:
    when: always
    paths:
      - _build/*.log

# TODO add Windows-package