

SET(CPACK_GENERATOR "TGZ")
SET(CPACK_SOURCE_GENERATOR "TGZ")

SET(CPACK_PACKAGE_FILE_NAME "${CPACK_PACKAGE_NAME}_${CPACK_PACKAGE_VERSION}_${OFBUILD_SYSTEM_ARCH}")

SET(CPACK_INCLUDE_TOPLEVEL_DIRECTORY 0)
