/**
  \file setup.h
  automatically generated by configure script.
*/

#ifndef __SETUP_H__
#define __SETUP_H__

#include <wx/string.h>

// Default directories
const wxString MHYDAS_DEFAULT_INDIR = wxT("MHYDAS.IN");
const wxString MHYDAS_DEFAULT_OUTDIR = wxT("MHYDAS.OUT");

// Default files
const wxString MHYDAS_DEFAULT_CONFFILE = wxT("config.xml");
const wxString MHYDAS_DEFAULT_INDATAFILE = wxT("inputdata.xml");
const wxString MHYDAS_DEFAULT_OUTRESFILE = wxT("outputres.xml");
const wxString MHYDAS_DEFAULT_SUDEFSFILE = wxT("SUdefs.dat");
const wxString MHYDAS_DEFAULT_RSDEFSFILE = wxT("RSdefs.dat");
const wxString MHYDAS_DEFAULT_GUDEFSFILE = wxT("GUdefs.dat");
const wxString MHYDAS_DEFAULT_RAINEVTFILE = wxT("rainevent.xml");
// File formats
const unsigned int MHYDAS_SUDEFSFILE_COLNBR = 8;
const unsigned int MHYDAS_RSDEFSFILE_COLNBR = 10;
const unsigned int MHYDAS_GUDEFSFILE_COLNBR = 4;

// Plugins extension
const wxString MHYDAS_PLUGINS_EXT = wxT("so");

// Plugins subdir
const wxString MHYDAS_PLUGINS_SUBDIR = wxT("plugs");

#endif

