\NeedsTeXFormat{LaTeX2e}

\ProvidesClass{openfluid-docalyzer}[Custom class for OpenFLUID docalyzer]

% base class
\LoadClass[a4paper,10pt]{article}

% packages
\RequirePackage[utf8x]{inputenc}
\RequirePackage[T1]{fontenc}
\RequirePackage[english]{babel}
\RequirePackage{tabularx}
\RequirePackage{hyperref}
\RequirePackage[margin=2cm]{geometry}
\RequirePackage{ucs}
\RequirePackage{graphicx}
\RequirePackage{xcolor}
\RequirePackage{cmbright} 
\RequirePackage{enumitem}
\RequirePackage{framed}

\hypersetup{
  colorlinks=true,
  urlcolor=magenta,
  linkcolor=magenta
}
