

OFBUILD_ADD_OBSERVER(export.vars.files.csv)
OFBUILD_ADD_OBSERVER(export.vars.files.csv-multicols)
OFBUILD_ADD_OBSERVER(export.vars.files.kml-anim)
OFBUILD_ADD_OBSERVER(export.vars.files.kml-plot)
OFBUILD_ADD_OBSERVER(export.vars.files.geovector)
OFBUILD_ADD_OBSERVER(export.vars.plot.gnuplot)
OFBUILD_ADD_OBSERVER(export.spatial-graph.files.dot)

INSTALL(DIRECTORY "${OFBUILD_DIST_OBSERVERS_DIR}/"
        DESTINATION "${OPENFLUID_OBSERVERS_INSTALL_PATH}")

SET(OFBUILD_SOURCE_OBSERVERS_DIR "${CMAKE_SOURCE_DIR}/src/${OPENFLUID_OBSERVERS_PATH}")

FILE(COPY "${OFBUILD_SOURCE_OBSERVERS_DIR}" 
     DESTINATION "${OFBUILD_DIST_DIR}/${OPENFLUID_EXAMPLES_WARESDEV_INSTALL_PATH}")

INSTALL(DIRECTORY "${OFBUILD_DIST_DIR}/${OPENFLUID_EXAMPLES_WARESDEV_INSTALL_PATH}"
        DESTINATION "${OPENFLUID_DOC_INSTALL_PATH}/")
