#! /bin/sh
# postrm script for libmhydasdk

set -e


case "$1" in
    remove|purge|update)

        /sbin/ldconfig

    ;;

    abort-remove|abort-upgrade|failed-upgrade)

    ;;


    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0;

