name: macOS

on: [push, pull_request]


jobs:


##########################################


  ci-macos-debug:
    strategy:
      matrix:
        os: [macos-12]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Installation of dependencies
        run: | 
          brew install \
            boost gdal curl qt6 \
            gnuplot
      - name: Checkout of source code
        uses: actions/checkout@v3
      - name: Preparation
        run: |
          echo "$(brew --prefix qt6)/bin" >> $GITHUB_PATH
          mkdir ./_build
      - name: Configuration
        run: cmake .. -DCMAKE_PREFIX_PATH=$(brew --prefix qt6)/lib/cmake
        working-directory: ./_build
      - name: Build
        run: make -j 2
        working-directory: ./_build
      - name: Testing
        run: ctest --output-on-failure
        working-directory: ./_build


##########################################


  ci-macos-release:
    strategy:
      matrix:
        os: [macos-12]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Installation of dependencies
        run: | 
          brew install \
            boost gdal curl qt6 \
            gnuplot
      - name: Checkout of source code
        uses: actions/checkout@v3
      - name: Preparation
        run: |
          echo "$(brew --prefix qt6)/bin" >> $GITHUB_PATH
          mkdir ./_build
      - name: Configuration
        run: cmake .. -DCMAKE_PREFIX_PATH=$(brew --prefix qt6)/lib/cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local
        working-directory: ./_build
      - name: Build
        run: make -j 2
        working-directory: ./_build