name: Ubuntu

on: [push, pull_request]


jobs:


##########################################


  ci-linux-debug-qt5:
    runs-on: ubuntu-22.04

    steps:
      - name: Installation of dependencies
        run: | 
          sudo apt update && sudo apt install -y \
            libboost-all-dev libgdal-dev libcurl4-gnutls-dev libgeos++-dev rapidjson-dev \
            libgl1-mesa-dev \
            qtbase5-dev qtbase5-dev-tools qttools5-dev qttools5-dev-tools libqt5svg5-dev libqt5webkit5-dev \
            gnuplot p7zip-full graphviz \
            doxygen texlive-latex-extra texlive-fonts-extra latex2html pandoc pandoc-citeproc
      - name: Checkout of source code
        uses: actions/checkout@v3
      - name: Preparation
        run: mkdir ./_build
      - name: Configuration
        run: cmake ..
        working-directory: ./_build
      - name: Build
        run: make -j 2
        working-directory: ./_build
      - name: Testing
        run: ctest -j 2 --output-on-failure
        working-directory: ./_build


##########################################


  ci-linux-debug-qt6:
    runs-on: ubuntu-22.04

    steps:
      - name: Installation of dependencies
        run: | 
          sudo apt update && sudo apt install -y \
            libboost-all-dev libgdal-dev libcurl4-gnutls-dev \
            libgl1-mesa-dev \
            qtchooser qt6-base-dev qt6-tools-dev libqt6svg6-dev qt6-l10n-tools qt6-base-dev-tools qt6-tools-dev-tools \
            libqt6uitools6 linguist-qt6 \
            libqt6core5compat6 libqt6gui6 \
            gnuplot p7zip-full graphviz \
            doxygen texlive-latex-extra texlive-fonts-extra latex2html pandoc pandoc-citeproc
      - name: Checkout of source code
        uses: actions/checkout@v3
      - name: Preparation
        run: mkdir ./_build
      - name: QtChooser
        run: qtchooser -install qt6 $(which qmake6)
      - name: Configuration
        run: cmake ..
        working-directory: ./_build
      - name: Build
        run: make -j 2
        working-directory: ./_build
        env:
          QT_SELECT: qt6
      - name: Testing
        run: ctest -j 2 --output-on-failure
        working-directory: ./_build


##########################################


  ci-linux-release-qt6:
    runs-on: ubuntu-22.04

    steps:
      - name: Installation of dependencies
        run: | 
          sudo apt update && sudo apt install -y \
            libboost-dev libgdal-dev libcurl4-gnutls-dev \
            libgl1-mesa-dev \
            qtchooser qt6-base-dev qt6-tools-dev libqt6svg6-dev qt6-l10n-tools qt6-base-dev-tools qt6-tools-dev-tools \
            libqt6uitools6 linguist-qt6 \
            libqt6core5compat6 libqt6gui6 \
            gnuplot p7zip-full graphviz
      - name: Checkout of source code
        uses: actions/checkout@v3
      - name: Preparation
        run: mkdir ./_build
      - name: QtChooser
        run: qtchooser -install qt6 $(which qmake6)
      - name: Configuration
        run: cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release
        working-directory: ./_build
      - name: Style check
        run: make stylecheck
        working-directory: ./_build
      - name: Build
        run: make -j 2
        working-directory: ./_build
        env:
          QT_SELECT: qt6
      - name: Packaging
        run: cpack && ls -l *.deb
        working-directory: ./_build
      - name: Upload of OpenFLUID package
        uses: actions/upload-artifact@v4
        with:
          name: deb-package-ubuntu-22.04-qt6
          path: ./_build/openfluid*.deb
          retention-days: 3


##########################################


  ci-linux-install-qt6:
    runs-on: ubuntu-22.04
    needs: ci-linux-release-qt6

    steps:
      - name: Download of OpenFLUID package
        uses: actions/download-artifact@v4
        with:
          name: deb-package-ubuntu-22.04-qt6
      - name: Installation of OpenFLUID package
        run: | 
          sudo apt update && sudo apt install -y ./openfluid*.deb
      - name: Check of OpenFLUID package
        run: | 
          openfluid version
          openfluid info


##########################################


  ci-linux-release-no-ui:
    strategy:
      matrix:
        os: [ubuntu-22.04,ubuntu-24.04]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Installation of dependencies
        run: | 
          sudo apt update && sudo apt install -y \
            libboost-dev libgdal-dev libcurl4-gnutls-dev \
            gnuplot p7zip-full graphviz
      - name: Checkout of source code
        uses: actions/checkout@v3
      - name: Preparation
        run: mkdir ./_build
      - name: Configuration
        run: cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release -DOFBUILD_ENABLE_GUI=OFF
        working-directory: ./_build
      - name: Style check
        run: make stylecheck
        working-directory: ./_build
      - name: Build
        run: make -j 2
        working-directory: ./_build
      - name: Packaging
        run: cpack && ls -l *.deb
        working-directory: ./_build
      - name: Upload of OpenFLUID package
        uses: actions/upload-artifact@v4
        with:
          name: deb-package-no-ui-${{ matrix.os }}
          path: ./_build/openfluid*.deb
          retention-days: 3


##########################################


  ci-linux-install-no-ui:
    strategy:
      matrix:
        os: [ubuntu-22.04,ubuntu-24.04]
    runs-on: ${{ matrix.os }}
    needs: ci-linux-release-no-ui

    steps:
      - name: Download of OpenFLUID package
        uses: actions/download-artifact@v4
        with:
          name: deb-package-no-ui-${{ matrix.os }}
      - name: Installation of OpenFLUID package
        run: | 
          sudo apt update && sudo apt install -y ./openfluid*.deb
      - name: Check of OpenFLUID package
        run: | 
          openfluid version
          openfluid info
