name: Ubuntu

on: [push, pull_request]


jobs:


##########################################


  ci-linux-debug:
    runs-on: ubuntu-20.04

    steps:
      - name: Installation of dependencies
        run: | 
          sudo apt update && sudo apt install -y \
            libboost-all-dev libgdal-dev libcurl4-gnutls-dev \
            qt5-default qtbase5-dev-tools qttools5-dev-tools libqt5svg5-dev \
            gnuplot p7zip-full graphviz
      - name: Checkout of source code
        uses: actions/checkout@v3
      - name: Preparation
        run: mkdir ./_build
      - name: Configuration
        run: cmake ..
        working-directory: ./_build
      - name: Build
        run: make -j 2
        working-directory: ./_build
      - name: Testing
        run: ctest -j 2 --output-on-failure
        working-directory: ./_build


##########################################


  ci-linux-release:
    runs-on: ubuntu-20.04

    steps:
      - name: Installation of dependencies
        run: | 
          sudo apt update && sudo apt install -y \
            libboost-dev libgdal-dev libcurl4-gnutls-dev \
            qt5-default qtbase5-dev-tools qttools5-dev-tools libqt5svg5-dev \
            gnuplot p7zip-full graphviz
      - name: Checkout of source code
        uses: actions/checkout@v3
      - name: Preparation
        run: mkdir ./_build
      - name: Configuration
        run: cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release
        working-directory: ./_build
      - name: Style check
        run: make stylecheck
        working-directory: ./_build
      - name: Build
        run: make -j 2
        working-directory: ./_build
      - name: Packaging
        run: cpack && ls -l *.deb
        working-directory: ./_build
      - name: Upload of OpenFLUID package
        uses: actions/upload-artifact@v3
        with:
          name: deb-package
          path: ./_build/openfluid*.deb
          retention-days: 3


##########################################


  ci-linux-install:
    runs-on: ubuntu-20.04
    needs: ci-linux-release

    steps:
      - name: Download of OpenFLUID package
        uses: actions/download-artifact@v3
        with:
          name: deb-package
      - name: Installation of OpenFLUID package
        run: | 
          sudo apt update && sudo apt install -y ./openfluid*.deb
      - name: Check of OpenFLUID package
        run: | 
          openfluid version
          openfluid info


##########################################


  ci-linux-release-no-ui:
    runs-on: ubuntu-20.04

    steps:
      - name: Installation of dependencies
        run: | 
          sudo apt update && sudo apt install -y \
            libboost-dev libgdal-dev libcurl4-gnutls-dev \
            gnuplot p7zip-full graphviz
      - name: Checkout of source code
        uses: actions/checkout@v3
      - name: Preparation
        run: mkdir ./_build
      - name: Configuration
        run: cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release -DOFBUILD_ENABLE_GUI=OFF
        working-directory: ./_build
      - name: Style check
        run: make stylecheck
        working-directory: ./_build
      - name: Build
        run: make -j 2
        working-directory: ./_build
      - name: Packaging
        run: cpack && ls -l *.deb
        working-directory: ./_build
      - name: Upload of OpenFLUID package
        uses: actions/upload-artifact@v3
        with:
          name: deb-package-no-ui
          path: ./_build/openfluid*.deb
          retention-days: 3


##########################################


  ci-linux-install-no-ui:
    runs-on: ubuntu-20.04
    needs: ci-linux-release-no-ui

    steps:
      - name: Download of OpenFLUID package
        uses: actions/download-artifact@v3
        with:
          name: deb-package-no-ui
      - name: Installation of OpenFLUID package
        run: | 
          sudo apt update && sudo apt install -y ./openfluid*.deb
      - name: Check of OpenFLUID package
        run: | 
          openfluid version
          openfluid info
