name: Windows

on: [push, pull_request]


jobs:


##########################################


  ci-windows-debug:
    runs-on: windows-2019
    
    defaults:
      run:
        shell: msys2 {0}
    
    steps:
      - name: Installation of dependencies
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: false
          release: false
          install: >-
            mingw-w64-x86_64-toolchain mingw-w64-x86_64-gcc mingw-w64-x86_64-gcc-fortran
            mingw-w64-x86_64-cmake mingw-w64-x86_64-doxygen
            mingw-w64-x86_64-boost mingw-w64-x86_64-gdal mingw-w64-x86_64-curl-winssl
            mingw-w64-x86_64-qt5 mingw-w64-x86_64-openssl
            git p7zip mingw-w64-x86_64-gnuplot mingw-w64-x86_64-graphviz
      - name: Checkout of source code
        uses: actions/checkout@v3
      - name: Preparation
        run: mkdir ./_build
      - name: Configuration
        run: cmake .. -G "MSYS Makefiles" -DOFBUILD_ENABLE_DOCS=OFF
        working-directory: ./_build
      - name: Build
        run: |
          export OPENFLUID_INSTALL_PREFIX=`pwd`/dist
          export PATH=$OPENFLUID_INSTALL_PREFIX/bin:$OPENFLUID_INSTALL_PREFIX/lib:$PATH
          make -j 2
        working-directory: ./_build
      - name: Testing
        run: |
          export OPENFLUID_INSTALL_PREFIX=`pwd`/dist
          export PATH=$OPENFLUID_INSTALL_PREFIX/bin:$OPENFLUID_INSTALL_PREFIX/lib:$PATH
          echo $PATH
          ctest -j 2 --output-on-failure
        working-directory: ./_build
